hydra:
  job:
    name : 'Hydra_${basename}_eval'
    chdir: true
    config:
      override_dirname:
        kv_sep: ':'
        item_sep: '__'
        exclude_keys:
          - data
          - eval.evaluation_mode 
  sweep:
    dir: ../${hydra.job.name}
    subdir: ${hydra.job.override_dirname}

basename: Grad-TTS_Hydra

data:

eval:
  split: test
  n_timesteps: 10
  Hydra_training_save: ../../Hydra_${basename}
  starting_epoch: 0
  ending_epoch: 1
  #checkpoint_dir: ${eval.Hydra_training_save}/${hydra:job.override_dirname}/${training.checkpoint_save}  
  checkpoint_dir: ../../${basename}/checkpts/GAM
  loc_train: ../../${basename}
  gt_dir: ground_truth
  cvt_dir: converted
  epoch_interval: 10
  evaluation_mode: 'WAVPDFMEL' #'LOSSES'
  gpu: 1
  spk: 0
  temperature: 1.5

model:
  spk_emb_dim: 128

  encoder:
    n_channels: 192
    filter_channels: 768
    filter_channels_dp: 256
    n_layers: 6
    kernel_size: 3
    p_dropout: 0.1
    n_heads: 2
    window_size: 4

  decoder:
    dim: 64
    beta_min: 0.05
    beta_max: 20.0
    pe_scale: 1000

  Masking:
    a: 0.05
    b: 0.01
    c: 0
    d: 0
    l: 1
    p: 0

training:
  load_encoder: True
  load_decoder: False
  train_encoder: False  
  n_timesteps: 10
  tensorboard_dir: tb
  start_checkpoint:
  pre_checkpoint: ../../${basename}/checkpts/a0.02b0.01_${training.start_checkpoint}.pt
  test_size: 1
  batch_size: 48
  n_epochs: 800
  learning_rate: 1e-4
  seed: 37
  save_every: 1
  gpu: 0
  num_workers: 4

